#define TRANSP 0
#define ORANGE 1
#define BROWN 2
#define CREAM 3
#define GREEN 4

unsigned int cat_1[8 * 8] = {
  TRANSP,TRANSP,TRANSP,TRANSP,ORANGE,TRANSP,TRANSP,BROWN,
    TRANSP,TRANSP,TRANSP,TRANSP,ORANGE,ORANGE,BROWN,BROWN,
    TRANSP,TRANSP,TRANSP,TRANSP,ORANGE,GREEN,BROWN,GREEN,
    ORANGE,BROWN,TRANSP,TRANSP,BROWN,ORANGE,CREAM,CREAM,
    TRANSP,ORANGE,TRANSP,BROWN,CREAM,CREAM,ORANGE,TRANSP,
    TRANSP,BROWN,ORANGE,CREAM,CREAM,CREAM,CREAM,TRANSP,
    TRANSP,TRANSP,ORANGE,ORANGE,BROWN,CREAM,BROWN,TRANSP,
    TRANSP,TRANSP,TRANSP,TRANSP,TRANSP,TRANSP,TRANSP,TRANSP
  };

  unsigned int cat_2[8*8] = {
    TRANSP,TRANSP,TRANSP,TRANSP,ORANGE,TRANSP,TRANSP,BROWN,
    TRANSP,TRANSP,TRANSP,TRANSP,ORANGE,ORANGE,BROWN,BROWN,
    TRANSP,ORANGE,TRANSP,TRANSP,ORANGE,GREEN,BROWN,GREEN,
    TRANSP,BROWN,TRANSP,TRANSP,BROWN,ORANGE,CREAM,CREAM,
    TRANSP,ORANGE,TRANSP,BROWN,CREAM,CREAM,ORANGE,TRANSP,
    TRANSP,BROWN,ORANGE,CREAM,CREAM,CREAM,CREAM,TRANSP,
    TRANSP,TRANSP,ORANGE,ORANGE,BROWN,CREAM,BROWN,TRANSP,
    TRANSP,TRANSP,TRANSP,TRANSP,TRANSP,TRANSP,TRANSP,TRANSP
  };

  unsigned int cat_3[8*8] = {
    TRANSP,TRANSP,TRANSP,TRANSP,ORANGE,TRANSP,TRANSP,BROWN,
    TRANSP,TRANSP,TRANSP,TRANSP,ORANGE,ORANGE,BROWN,BROWN,
    TRANSP,TRANSP,TRANSP,TRANSP,ORANGE,GREEN,BROWN,GREEN,
    TRANSP,BROWN,ORANGE,TRANSP,BROWN,ORANGE,CREAM,CREAM,
    TRANSP,ORANGE,TRANSP,BROWN,CREAM,CREAM,ORANGE,TRANSP,
    TRANSP,BROWN,ORANGE,CREAM,CREAM,CREAM,CREAM,TRANSP,
    TRANSP,TRANSP,ORANGE,ORANGE,BROWN,CREAM,BROWN,TRANSP,
    TRANSP,TRANSP,TRANSP,TRANSP,TRANSP,TRANSP,TRANSP,TRANSP
  };  